package com.ray.entity.mapper;

import com.ray.entity.AlertType;
import com.ray.entity.AlertTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AlertTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @SelectProvider(type=AlertTypeSqlProvider.class, method="countByExample")
    int countByExample(AlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @DeleteProvider(type=AlertTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(AlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @Delete({
        "delete from alerttype",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @Insert({
        "insert into alerttype (id, name, ",
        "param1, param2)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{param1,jdbcType=VARCHAR}, #{param2,jdbcType=VARCHAR})"
    })
    int insert(AlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @InsertProvider(type=AlertTypeSqlProvider.class, method="insertSelective")
    int insertSelective(AlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @SelectProvider(type=AlertTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="param1", property="param1", jdbcType=JdbcType.VARCHAR),
        @Result(column="param2", property="param2", jdbcType=JdbcType.VARCHAR)
    })
    List<AlertType> selectByExample(AlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, param1, param2",
        "from alerttype",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="param1", property="param1", jdbcType=JdbcType.VARCHAR),
        @Result(column="param2", property="param2", jdbcType=JdbcType.VARCHAR)
    })
    AlertType selectByPrimaryKey(Integer id);

    @SelectProvider(type=DynamicSql.class,method="getSql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="param1", property="param1", jdbcType=JdbcType.VARCHAR),
        @Result(column="param2", property="param2", jdbcType=JdbcType.VARCHAR)
    })
    List<AlertType> selectByDynamicSQL();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AlertTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AlertType record, @Param("example") AlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AlertTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AlertType record, @Param("example") AlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AlertTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerttype
     *
     * @mbggenerated
     */
    @Update({
        "update alerttype",
        "set name = #{name,jdbcType=VARCHAR},",
          "param1 = #{param1,jdbcType=VARCHAR},",
          "param2 = #{param2,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AlertType record);
}