package com.ray.entity.mapper;

import com.ray.entity.Commend;
import com.ray.entity.CommendCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @SelectProvider(type=CommendSqlProvider.class, method="countByExample")
    int countByExample(CommendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @DeleteProvider(type=CommendSqlProvider.class, method="deleteByExample")
    int deleteByExample(CommendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @Delete({
        "delete from commend",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @Insert({
        "insert into commend (id, email, ",
        "nickname, commend, ",
        "createtime)",
        "values (#{id,jdbcType=INTEGER}, #{email,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{commend,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP})"
    })
    int insert(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @InsertProvider(type=CommendSqlProvider.class, method="insertSelective")
    int insertSelective(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @SelectProvider(type=CommendSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="commend", property="commend", jdbcType=JdbcType.VARCHAR),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Commend> selectByExample(CommendCriteria example);
    
    @SelectProvider(type=DynamicSql.class,method="getSql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="commend", property="commend", jdbcType=JdbcType.VARCHAR),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Commend> selectByPage();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, email, nickname, commend, createtime",
        "from commend",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="commend", property="commend", jdbcType=JdbcType.VARCHAR),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP)
    })
    Commend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CommendSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Commend record, @Param("example") CommendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CommendSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Commend record, @Param("example") CommendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CommendSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated
     */
    @Update({
        "update commend",
        "set email = #{email,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "commend = #{commend,jdbcType=VARCHAR},",
          "createtime = #{createtime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Commend record);
}