package com.ray.entity.mapper;

import com.ray.entity.Css;
import com.ray.entity.CssCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @SelectProvider(type=CssSqlProvider.class, method="countByExample")
    int countByExample(CssCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @DeleteProvider(type=CssSqlProvider.class, method="deleteByExample")
    int deleteByExample(CssCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @Delete({
        "delete from css",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @Insert({
        "insert into css (id, res_link_id, ",
        "csslink)",
        "values (#{id,jdbcType=INTEGER}, #{resLinkId,jdbcType=INTEGER}, ",
        "#{csslink,jdbcType=VARCHAR})"
    })
    int insert(Css record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @InsertProvider(type=CssSqlProvider.class, method="insertSelective")
    int insertSelective(Css record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @SelectProvider(type=CssSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="res_link_id", property="resLinkId", jdbcType=JdbcType.INTEGER),
        @Result(column="csslink", property="csslink", jdbcType=JdbcType.VARCHAR)
    })
    List<Css> selectByExample(CssCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, res_link_id, csslink",
        "from css",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="res_link_id", property="resLinkId", jdbcType=JdbcType.INTEGER),
        @Result(column="csslink", property="csslink", jdbcType=JdbcType.VARCHAR)
    })
    Css selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CssSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Css record, @Param("example") CssCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CssSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Css record, @Param("example") CssCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @UpdateProvider(type=CssSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Css record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table css
     *
     * @mbggenerated
     */
    @Update({
        "update css",
        "set res_link_id = #{resLinkId,jdbcType=INTEGER},",
          "csslink = #{csslink,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Css record);
}