package com.ray.entity.mapper;

import com.ray.entity.ResLink;
import com.ray.entity.ResLinkCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ResLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @SelectProvider(type=ResLinkSqlProvider.class, method="countByExample")
    int countByExample(ResLinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @DeleteProvider(type=ResLinkSqlProvider.class, method="deleteByExample")
    int deleteByExample(ResLinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @Delete({
        "delete from res_link",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @Insert({
        "insert into res_link (id, name, ",
        "url, resid, typeid)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{resid,jdbcType=INTEGER}, #{typeid,jdbcType=INTEGER})"
    })
    int insert(ResLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @InsertProvider(type=ResLinkSqlProvider.class, method="insertSelective")
    int insertSelective(ResLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @SelectProvider(type=ResLinkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="resid", property="resid", jdbcType=JdbcType.INTEGER),
        @Result(column="typeid", property="typeid", jdbcType=JdbcType.INTEGER)
    })
    List<ResLink> selectByExample(ResLinkCriteria example);
    
    @SelectProvider(type=DynamicSql.class,method="getSql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="resid", property="resid", jdbcType=JdbcType.INTEGER),
        @Result(column="typeid", property="typeid", jdbcType=JdbcType.INTEGER),
        @Result(column="title",property="title",jdbcType=JdbcType.VARCHAR)
    })
    List<ResLink> selectAll();
    
    @SelectProvider(type=DynamicSql.class,method="getSql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="resid", property="resid", jdbcType=JdbcType.INTEGER),
        @Result(column="typeid", property="typeid", jdbcType=JdbcType.INTEGER),
        @Result(column="title",property="title",jdbcType=JdbcType.VARCHAR)
    })
    List<ResLink> selectByPage();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, url, resid, typeid",
        "from res_link",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="resid", property="resid", jdbcType=JdbcType.INTEGER),
        @Result(column="typeid", property="typeid", jdbcType=JdbcType.INTEGER)
    })
    ResLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResLinkSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ResLink record, @Param("example") ResLinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResLinkSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ResLink record, @Param("example") ResLinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResLinkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ResLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_link
     *
     * @mbggenerated
     */
    @Update({
        "update res_link",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "resid = #{resid,jdbcType=INTEGER},",
          "typeid = #{typeid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ResLink record);
}