package com.ray.entity.mapper;

import com.ray.entity.Res;
import com.ray.entity.ResCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @SelectProvider(type=ResSqlProvider.class, method="countByExample")
    int countByExample(ResCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @DeleteProvider(type=ResSqlProvider.class, method="deleteByExample")
    int deleteByExample(ResCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Delete({
        "delete from res",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Insert({
        "insert into res (id, name, ",
        "url)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR})"
    })
    int insert(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @InsertProvider(type=ResSqlProvider.class, method="insertSelective")
    int insertSelective(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @SelectProvider(type=ResSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    List<Res> selectByExample(ResCriteria example);
    
    @SelectProvider(type=DynamicSql.class, method="getSql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    List<Res> selectByPage();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, url",
        "from res",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    Res selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Res record, @Param("example") ResCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Res record, @Param("example") ResCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ResSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Update({
        "update res",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Res record);
}