package com.ray.entity;

public class AlertType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerttype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerttype.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerttype.param1
     *
     * @mbggenerated
     */
    private String param1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerttype.param2
     *
     * @mbggenerated
     */
    private String param2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerttype.id
     *
     * @return the value of alerttype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerttype.id
     *
     * @param id the value for alerttype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerttype.name
     *
     * @return the value of alerttype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerttype.name
     *
     * @param name the value for alerttype.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerttype.param1
     *
     * @return the value of alerttype.param1
     *
     * @mbggenerated
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerttype.param1
     *
     * @param param1 the value for alerttype.param1
     *
     * @mbggenerated
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerttype.param2
     *
     * @return the value of alerttype.param2
     *
     * @mbggenerated
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerttype.param2
     *
     * @param param2 the value for alerttype.param2
     *
     * @mbggenerated
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }
}