package com.ray.entity;

import java.util.Date;

public class Alert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.desc1
     *
     * @mbggenerated
     */
    private String desc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.res_link_id
     *
     * @mbggenerated
     */
    private Integer resLinkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.res_id
     *
     * @mbggenerated
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.atype_id
     *
     * @mbggenerated
     */
    private Integer atypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.hot
     *
     * @mbggenerated
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.alerttime
     *
     * @mbggenerated
     */
    private String alerttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.param1
     *
     * @mbggenerated
     */
    private String param1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.param2
     *
     * @mbggenerated
     */
    private String param2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.param3
     *
     * @mbggenerated
     */
    private String param3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.param4
     *
     * @mbggenerated
     */
    private String param4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.param5
     *
     * @mbggenerated
     */
    private String param5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.id
     *
     * @return the value of alert.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.id
     *
     * @param id the value for alert.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.title
     *
     * @return the value of alert.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.title
     *
     * @param title the value for alert.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.desc1
     *
     * @return the value of alert.desc1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.desc1
     *
     * @param desc1 the value for alert.desc1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.url
     *
     * @return the value of alert.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.url
     *
     * @param url the value for alert.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.res_link_id
     *
     * @return the value of alert.res_link_id
     *
     * @mbggenerated
     */
    public Integer getResLinkId() {
        return resLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.res_link_id
     *
     * @param resLinkId the value for alert.res_link_id
     *
     * @mbggenerated
     */
    public void setResLinkId(Integer resLinkId) {
        this.resLinkId = resLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.res_id
     *
     * @return the value of alert.res_id
     *
     * @mbggenerated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.res_id
     *
     * @param resId the value for alert.res_id
     *
     * @mbggenerated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.atype_id
     *
     * @return the value of alert.atype_id
     *
     * @mbggenerated
     */
    public Integer getAtypeId() {
        return atypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.atype_id
     *
     * @param atypeId the value for alert.atype_id
     *
     * @mbggenerated
     */
    public void setAtypeId(Integer atypeId) {
        this.atypeId = atypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.hot
     *
     * @return the value of alert.hot
     *
     * @mbggenerated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.hot
     *
     * @param hot the value for alert.hot
     *
     * @mbggenerated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.createtime
     *
     * @return the value of alert.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.createtime
     *
     * @param createtime the value for alert.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.alerttime
     *
     * @return the value of alert.alerttime
     *
     * @mbggenerated
     */
    public String getAlerttime() {
        return alerttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.alerttime
     *
     * @param alerttime the value for alert.alerttime
     *
     * @mbggenerated
     */
    public void setAlerttime(String alerttime) {
        this.alerttime = alerttime == null ? null : alerttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.param1
     *
     * @return the value of alert.param1
     *
     * @mbggenerated
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.param1
     *
     * @param param1 the value for alert.param1
     *
     * @mbggenerated
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.param2
     *
     * @return the value of alert.param2
     *
     * @mbggenerated
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.param2
     *
     * @param param2 the value for alert.param2
     *
     * @mbggenerated
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.param3
     *
     * @return the value of alert.param3
     *
     * @mbggenerated
     */
    public String getParam3() {
        return param3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.param3
     *
     * @param param3 the value for alert.param3
     *
     * @mbggenerated
     */
    public void setParam3(String param3) {
        this.param3 = param3 == null ? null : param3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.param4
     *
     * @return the value of alert.param4
     *
     * @mbggenerated
     */
    public String getParam4() {
        return param4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.param4
     *
     * @param param4 the value for alert.param4
     *
     * @mbggenerated
     */
    public void setParam4(String param4) {
        this.param4 = param4 == null ? null : param4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.param5
     *
     * @return the value of alert.param5
     *
     * @mbggenerated
     */
    public String getParam5() {
        return param5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.param5
     *
     * @param param5 the value for alert.param5
     *
     * @mbggenerated
     */
    public void setParam5(String param5) {
        this.param5 = param5 == null ? null : param5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert.content
     *
     * @return the value of alert.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert.content
     *
     * @param content the value for alert.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}