package com.ray.entity;

public class Appusers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appusers.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appusers.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appusers.AccessToken
     *
     * @mbggenerated
     */
    private String accesstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appusers.ExpiresIn
     *
     * @mbggenerated
     */
    private String expiresin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appusers.id
     *
     * @return the value of appusers.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appusers.id
     *
     * @param id the value for appusers.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appusers.openid
     *
     * @return the value of appusers.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appusers.openid
     *
     * @param openid the value for appusers.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appusers.AccessToken
     *
     * @return the value of appusers.AccessToken
     *
     * @mbggenerated
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appusers.AccessToken
     *
     * @param accesstoken the value for appusers.AccessToken
     *
     * @mbggenerated
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken == null ? null : accesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appusers.ExpiresIn
     *
     * @return the value of appusers.ExpiresIn
     *
     * @mbggenerated
     */
    public String getExpiresin() {
        return expiresin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appusers.ExpiresIn
     *
     * @param expiresin the value for appusers.ExpiresIn
     *
     * @mbggenerated
     */
    public void setExpiresin(String expiresin) {
        this.expiresin = expiresin == null ? null : expiresin.trim();
    }
}