package com.ray.entity;

public class Appversion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.nametype
     *
     * @mbggenerated
     */
    private Integer nametype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.id
     *
     * @return the value of appversion.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.id
     *
     * @param id the value for appversion.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.version
     *
     * @return the value of appversion.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.version
     *
     * @param version the value for appversion.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.url
     *
     * @return the value of appversion.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.url
     *
     * @param url the value for appversion.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.des
     *
     * @return the value of appversion.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.des
     *
     * @param des the value for appversion.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.nametype
     *
     * @return the value of appversion.nametype
     *
     * @mbggenerated
     */
    public Integer getNametype() {
        return nametype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.nametype
     *
     * @param nametype the value for appversion.nametype
     *
     * @mbggenerated
     */
    public void setNametype(Integer nametype) {
        this.nametype = nametype;
    }
}