package com.ray.entity;

import java.util.Date;

public class Commend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.commend
     *
     * @mbggenerated
     */
    private String commend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.id
     *
     * @return the value of commend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.id
     *
     * @param id the value for commend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.email
     *
     * @return the value of commend.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.email
     *
     * @param email the value for commend.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.nickname
     *
     * @return the value of commend.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.nickname
     *
     * @param nickname the value for commend.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.commend
     *
     * @return the value of commend.commend
     *
     * @mbggenerated
     */
    public String getCommend() {
        return commend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.commend
     *
     * @param commend the value for commend.commend
     *
     * @mbggenerated
     */
    public void setCommend(String commend) {
        this.commend = commend == null ? null : commend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.createtime
     *
     * @return the value of commend.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.createtime
     *
     * @param createtime the value for commend.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}