package com.ray.entity;

import java.util.Date;

public class Favorites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.articleid
     *
     * @mbggenerated
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.createtime
     *
     * @mbggenerated
     */
    private Date createtime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.desc1
     *
     * @mbggenerated
     */
    private String desc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert.url
     *
     * @mbggenerated
     */
    private String url;
    private String param1;
    
    private String img;
    

    public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDesc1() {
		return desc1;
	}

	public void setDesc1(String desc1) {
		this.desc1 = desc1;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getParam1() {
		return param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.id
     *
     * @return the value of favorites.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.id
     *
     * @param id the value for favorites.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.openid
     *
     * @return the value of favorites.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.openid
     *
     * @param openid the value for favorites.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.articleid
     *
     * @return the value of favorites.articleid
     *
     * @mbggenerated
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.articleid
     *
     * @param articleid the value for favorites.articleid
     *
     * @mbggenerated
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.createtime
     *
     * @return the value of favorites.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.createtime
     *
     * @param createtime the value for favorites.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}