package com.ray.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.fromopenid
     *
     * @mbggenerated
     */
    private String fromopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.toopenid
     *
     * @mbggenerated
     */
    private String toopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgtype
     *
     * @mbggenerated
     */
    private Integer msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.fromopenid
     *
     * @return the value of message.fromopenid
     *
     * @mbggenerated
     */
    public String getFromopenid() {
        return fromopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.fromopenid
     *
     * @param fromopenid the value for message.fromopenid
     *
     * @mbggenerated
     */
    public void setFromopenid(String fromopenid) {
        this.fromopenid = fromopenid == null ? null : fromopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.toopenid
     *
     * @return the value of message.toopenid
     *
     * @mbggenerated
     */
    public String getToopenid() {
        return toopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.toopenid
     *
     * @param toopenid the value for message.toopenid
     *
     * @mbggenerated
     */
    public void setToopenid(String toopenid) {
        this.toopenid = toopenid == null ? null : toopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgtype
     *
     * @return the value of message.msgtype
     *
     * @mbggenerated
     */
    public Integer getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgtype
     *
     * @param msgtype the value for message.msgtype
     *
     * @mbggenerated
     */
    public void setMsgtype(Integer msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createtime
     *
     * @return the value of message.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createtime
     *
     * @param createtime the value for message.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}