package com.ray.entity;

public class ResLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_link.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_link.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_link.resid
     *
     * @mbggenerated
     */
    private Integer resid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_link.id
     *
     * @return the value of res_link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_link.id
     *
     * @param id the value for res_link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_link.name
     *
     * @return the value of res_link.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_link.name
     *
     * @param name the value for res_link.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_link.url
     *
     * @return the value of res_link.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_link.url
     *
     * @param url the value for res_link.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_link.resid
     *
     * @return the value of res_link.resid
     *
     * @mbggenerated
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_link.resid
     *
     * @param resid the value for res_link.resid
     *
     * @mbggenerated
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }
}