package com.ray.entity;

public class Tem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tem.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tem.id
     *
     * @return the value of tem.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tem.id
     *
     * @param id the value for tem.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}