package com.ray.entity;

public class UserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.issuccess
     *
     * @mbggenerated
     */
    private Integer issuccess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.id
     *
     * @return the value of userlog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.id
     *
     * @param id the value for userlog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.username
     *
     * @return the value of userlog.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.username
     *
     * @param username the value for userlog.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.ip
     *
     * @return the value of userlog.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.ip
     *
     * @param ip the value for userlog.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.issuccess
     *
     * @return the value of userlog.issuccess
     *
     * @mbggenerated
     */
    public Integer getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.issuccess
     *
     * @param issuccess the value for userlog.issuccess
     *
     * @mbggenerated
     */
    public void setIssuccess(Integer issuccess) {
        this.issuccess = issuccess;
    }
}